// user-profile/nuxt/pages/auth/signup.vue
<script setup lang="ts">
import { z, ZodError } from 'zod';
import { AuthUserSchema } from '~/lib/validationSchema';
import { formatError } from '~/lib/utils';

definePageMeta({
    layout: "auth",
});

type FormData = z.infer<typeof AuthUserSchema>;

const supabase = useSupabaseClient();
const formData = reactive<FormData>({
    email: "",
    password: ""
});
const errors = reactive<FormData>({
    email: "",
    password: ""
});
const message = ref("");
const formSuccess = ref(false);

const setErrors = (data: FormData) => {
    errors.email = data.email
    errors.password = data.password
}

const handleSubmit = async () => {
    // reset all states
    formSuccess.value = false;
    setErrors({ email: "", password: "" });
    message.value = "";

    try {
        AuthUserSchema.parse(formData);
    } catch (err) {
        if (err instanceof ZodError) {
            const errs = formatError(err) as FormData;
            setErrors(errs);
            return;
        }
    }

    const { error } = await supabase.auth.signUp({
        email: formData.email,
        password: formData.password,
        options: {
            emailRedirectTo: `${useRuntimeConfig().public.baseUrl}/auth/confirm`,
        }
    });

    if (error) {
        message.value = error.message;
        return;
    }

    // reset form
    formData.email = "";
    formData.password = "";
    formSuccess.value = true;
    message.value = "Please check your email for a magic link to log into the website.";
}
</script>

<template>
    <div class="w-11/12 p-12 px-6 py-10 rounded-lg sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-3/12 sm:px-10 sm:py-6">
        <Alert v-if="message" class="mb-10" :class="{ 'alert-info': formSuccess, 'alert-error': !formSuccess }">
            {{ message }}
        </Alert>
        <h2 class="font-semibold text-4xl mb-4">Create an account</h2>
        <p class="font-medium mb-4">Let's get started</p>
        <form @submit.prevent="handleSubmit">
            <div class="form-control">
                <label for="email" class="label">Email</label>
                <input id="email" name="email" type="text" v-model="formData.email" class="input input-bordered" />
            </div>
            <InputErrorMessage v-if="errors.email">{{ errors.email }}</InputErrorMessage>
            <div class="form-control">
                <label for="password" class="label">Password</label>
                <input id="password" name="password" type="password" v-model="formData.password"
                    class="input input-bordered" />
            </div>
            <InputErrorMessage v-if="errors.password">{{ errors.password }}</InputErrorMessage>
            <div class="form-control mt-6">
                <button class="btn btn-primary no-animation">Create account</button>
            </div>
        </form>
        <div class="pt-4 text-center">
            Already have an account? <NuxtLink to="/auth/signin" class="underline text-blue-500">Sign In</NuxtLink>
        </div>
    </div>
</template>

// user-profile/react/src/routes/auth/signup.tsx
import { FormEvent, useState } from "react";
import { AuthUserSchema } from "@/lib/validationSchema";
import { z, ZodError } from "zod";
import { formatError } from "@/lib/utils";
import InputErrorMessage from "@/components/InputErrorMessage";
import { AuthApiError } from "@supabase/supabase-js";
import Alert from "@/components/Alert";
import { Link } from "react-router-dom";
import { useSupabaseClient } from "@/lib/AuthProvider";

type FormData = z.infer<typeof AuthUserSchema>;

export default function SignUp() {
  const supabase = useSupabaseClient();
  const [errors, setErrors] = useState<FormData>();
  const [message, setMessage] = useState<string>("");
  const [formSuccess, setFormSuccess] = useState(false);
  const [formData, setFormData] = useState<FormData>({
    email: "",
    password: "",
  });

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    // reset all states
    setFormSuccess(false);
    setErrors(undefined);
    setMessage("");

    const email = formData.email;
    const password = formData.password;

    try {
      AuthUserSchema.parse({ email, password });
    } catch (err) {
      if (err instanceof ZodError) {
        const errs = formatError(err) as FormData;
        setErrors(errs);
        return;
      }
    }
    const { error } = await supabase.auth.signUp({
      email,
      password,
    });

    if (error) {
      if (error instanceof AuthApiError && error.status === 400) {
        setMessage("Invalid credentials.");
        return;
      }
      setMessage(error.message);
      return;
    }

    // reset form
    setFormData({ email: "", password: "" });
    setFormSuccess(true);
    setMessage(
      "Please check your email for a magic link to log into the website."
    );
  };

  return (
    <>
      <div className="w-11/12 p-12 px-6 py-10 rounded-lg sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-3/12 sm:px-10 sm:py-6">
        {message ? (
          <Alert
            className={`${formSuccess ? "alert-info" : "alert-error"} mb-10`}
          >
            {message}
          </Alert>
        ) : null}
        <h2 className="font-semibold text-4xl mb-4">Sign up</h2>
        <p className="font-medium mb-4">Let's get started</p>
        <form onSubmit={handleSubmit}>
          <div className="form-control">
            <label htmlFor="email" className="label">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="text"
              value={formData?.email ?? ""}
              onChange={(ev) =>
                setFormData({ ...formData, email: ev.target.value })
              }
              className="input input-bordered"
            />
          </div>
          {errors?.email ? (
            <InputErrorMessage>{errors?.email}</InputErrorMessage>
          ) : null}
          <div className="form-control">
            <label htmlFor="password" className="label">
              Password
            </label>
            <input
              id="password"
              name="password"
              type="password"
              value={formData.password}
              onChange={(ev) =>
                setFormData({ ...formData, password: ev.target.value })
              }
              className="input input-bordered"
            />
          </div>
          {errors?.password ? (
            <InputErrorMessage>{errors?.password}</InputErrorMessage>
          ) : null}
          <div className="form-control mt-6">
            <button className="btn btn-primary no-animation">
              Create account
            </button>
          </div>
        </form>
        <div className="pt-4 text-center">
          Already have an account?{" "}
          <Link to="/auth/signin" className="underline text-blue-500">
            Sign In
          </Link>
        </div>
      </div>
    </>
  );
}
