// magic-link/nuxt/pages/auth/signin.vue
<script setup lang="ts">
import { z, ZodError } from 'zod'
import { AuthUserSchema } from '~/lib/validationSchema'
import { formatError } from '~/lib/utils';

definePageMeta({
    layout: "auth",
})

type FormData = z.infer<typeof AuthUserSchema>

const supabase = useSupabaseClient()
const formData = reactive<FormData>({
    email: ""
})
const errors = reactive<FormData>({
    email: ""
})
const message = ref("")
const formSuccess = ref(false)

const setErrors = (data: FormData) => {
    errors.email = data.email
}

const handleSubmit = async () => {
    // reset all states
    formSuccess.value = false
    setErrors({ email: "" })
    message.value = ""

    try {
        AuthUserSchema.parse(formData)
    } catch (err) {
        if (err instanceof ZodError) {
            const errs = formatError(err) as FormData
            setErrors(errs)
            return
        }
    }

    const { error } = await supabase.auth.signInWithOtp({
        email: formData.email,
        options: {
            emailRedirectTo: `${useRuntimeConfig().public.baseUrl}/auth/confirm`
        }
    })

    if (error) {
        message.value = error.message
        return
    }

    // reset form
    formData.email = ""
    formSuccess.value = true
    message.value = "Please check your email for a magic link to log into the website."
}
</script>

<template>
    <div class="w-11/12 p-12 px-6 py-10 rounded-lg sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-3/12 sm:px-10 sm:py-6">
        <Alert v-if="message" class="mb-10" :class="{ 'alert-info': formSuccess, 'alert-error': !formSuccess }">
            {{ message }}
        </Alert>
        <h2 class="font-semibold text-4xl mb-4">Sign in</h2>
        <p class="font-medium mb-4">Hi, Welcome back</p>
        <form @submit.prevent="handleSubmit">
            <div class="form-control">
                <label for="email" class="label">Email</label>
                <input id="email" name="email" type="text" v-model="formData.email" class="input input-bordered" />
            </div>
            <InputErrorMessage v-if="errors.email">{{ errors.email }}</InputErrorMessage>
            <div class="form-control mt-6">
                <button class="btn btn-primary no-animation">Sign in</button>
            </div>
        </form>
    </div>
</template>

// magic-link/nextjs/pages/auth/signin.tsx
import Head from "next/head";
import AuthLayout from "@/components/AuthLayout";
import { FormEvent, useState } from "react";
import { AuthUserSchema } from "@/lib/validationSchema";
import { z, ZodError } from "zod";
import { formatError } from "@/lib/utils";
import InputErrorMessage from "@/components/InputErrorMessage";
import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { AuthApiError } from "@supabase/supabase-js";
import Alert from "@/components/Alert";
import { useRouter } from "next/router";

type FormData = z.infer<typeof AuthUserSchema>;

export default function SignIn() {
  const supabase = useSupabaseClient();
  const router = useRouter();
  const [errors, setErrors] = useState<FormData>();
  const [message, setMessage] = useState<string>("");
  const [formSuccess, setFormSuccess] = useState(false);
  const [formData, setFormData] = useState<FormData>({
    email: "",
  });

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    // reset all states
    setFormSuccess(false);
    setErrors(undefined);
    setMessage("");

    const email = formData.email;

    try {
      AuthUserSchema.parse({ email });
    } catch (err) {
      if (err instanceof ZodError) {
        const errs = formatError(err) as FormData;
        setErrors(errs);
        return;
      }
    }

    const { error } = await supabase.auth.signInWithOtp({
      email,
      options: {
        emailRedirectTo: `${
          new URL(location.href).origin
        }/logging-in?redirect=/`,
      },
    });

    if (error) {
      if (error instanceof AuthApiError && error.status === 400) {
        setMessage("Invalid credentials.");
        return;
      }
      setMessage(error.message);
      return;
    }

    // reset form
    setFormData({ email: "" });
    setFormSuccess(true);
    setMessage(
      "Please check your email for a magic link to log into the website."
    );
  };

  return (
    <>
      <AuthLayout>
        <div className="w-11/12 p-12 px-6 py-10 rounded-lg sm:w-8/12 md:w-6/12 lg:w-5/12 2xl:w-3/12 sm:px-10 sm:py-6">
          {message ? (
            <Alert
              className={`${formSuccess ? "alert-info" : "alert-error"} mb-10`}
            >
              {message}
            </Alert>
          ) : null}
          <h2 className="font-semibold text-4xl mb-4">Sign in</h2>
          <p className="font-medium mb-4">Hi, Welcome back</p>
          <form onSubmit={handleSubmit}>
            <div className="form-control">
              <label htmlFor="email" className="label">
                Email
              </label>
              <input
                id="email"
                name="email"
                type="text"
                value={formData?.email ?? ""}
                onChange={(ev) =>
                  setFormData({ ...formData, email: ev.target.value })
                }
                className="input input-bordered"
              />
            </div>
            {errors?.email ? (
              <InputErrorMessage>{errors?.email}</InputErrorMessage>
            ) : null}
            <div className="form-control mt-6">
              <button className="btn btn-primary no-animation">Sign in</button>
            </div>
          </form>
        </div>
      </AuthLayout>
    </>
  );
}
